# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: false

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers:
  - r21gh  # Replace with actual reviewer usernames

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers
numberOfReviewers: 1

# A list of assignees, overrides reviewers if set
assignees:
  - r21gh  # Replace with actual assignee usernames

# A number of assignees to add to the pull request
# Set to 0 to add all of the assignees.
# Uses numberOfReviewers if unset.
numberOfAssignees: 1

# A list of keywords to be skipped the process that add reviewers if pull requests include it
skipKeywords:
  - wip
  - draft 