apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-registry-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }} 