apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flask-app.fullname" . }}-secrets
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.secretKey | default "dev-secret-key" | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | default "dev-password" | quote }}
  API_BASE_URL: {{ .Values.env.apiBaseUrl | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}