apiVersion: v1
kind: Secret
metadata:
  # The name of the Secret is derived from the full name of the application
  name: {{ include "flask-app.fullname" . }}-secrets
  labels:
    # Include predefined labels from the chart's "labels" helper for consistency and management
    {{- include "flask-app.labels" . | nindent 4 }}
type: Opaque
data:
  # The secret key is encoded in base64 and stored securely in the secret
  secret-key: {{ .Values.secrets.secretKey | b64enc | quote }}
  # The database password is also encoded in base64 and stored securely
  db-password: {{ .Values.secrets.dbPassword | b64enc | quote }}
