apiVersion: v1
kind: Service
metadata:
  # The name of the service will be based on the full chart name.
  name: {{ include "flask-app.fullname" . }}
  labels:
    # Labels are included for easier management and identification of the service.
    {{- include "flask-app.labels" . | nindent 4 }}
spec:
  # The type of service determines how it is exposed within the cluster.
  # Options include ClusterIP, NodePort, or LoadBalancer.
  type: {{ .Values.service.type }}
  
  ports:
    # Define the port configuration for the service.
    - port: {{ .Values.service.port }}  # The port exposed by the service
      targetPort: http  # The target port on the container (named 'http' in the container spec)
      protocol: TCP  # Protocol used by the service (TCP is default for HTTP services)
      name: http  # The name of the port, typically used by ingress controllers or other components.
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      
  # The selector specifies the labels used to identify the set of Pods that this service should route traffic to.
  selector:
    # Selector ensures the service routes traffic only to pods matching these labels.
    {{- include "flask-app.selectorLabels" . | nindent 4 }}
