{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  # The name of the service account will be based on the chart's service account name template.
  name: {{ include "flask-app.serviceAccountName" . }}
  
  labels:
    # Labels help categorize and manage the service account. These are inherited from the chart's labels.
    {{- include "flask-app.labels" . | nindent 4 }}

  # Annotations provide additional metadata, such as configuration or documentation.
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    # Annotations are applied if any are defined in the values.yaml file.
    {{- toYaml . | nindent 4 }}
  {{- end }}

# Specifies whether the service account token is automatically mounted into pods.
# Setting this to false is useful when the pod doesn't need a default service account token.
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
