{{- if .Values.monitoring.enabled }}
# Storage Class for monitoring components
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Release.Name }}-monitoring-sc
provisioner: rancher.io/local-path  # Local path provisioner for development
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
{{- end }} 