server:
  global:
    scrape_interval: 15s
    evaluation_interval: 15s

  persistentVolume:
    size: 10Gi

  retention: 15d

  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

alertmanager:
  enabled: true
  persistentVolume:
    size: 2Gi

pushgateway:
  enabled: true

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true 