name: Deploy to Production

on:
  workflow_run:
    workflows: ["Deploy to Staging"]
    types:
      - completed
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: production
      url: https://prod.your-domain.com  # Replace with your actual production URL
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure kubectl
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG_PROD }}
        
    - name: Deploy to production environment
      run: |
        helm upgrade --install flask-app ./helm-charts \
          --namespace prod-flask-app \
          --create-namespace \
          --values ./helm-charts/values-prod.yaml \
          --set image.repository=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} \
          --set image.tag=${{ github.sha }} 