name: Terraform

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'terraform/**'

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go-Task
        uses: arduino/setup-task@v1
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.0.0"

      - name: Verify Terraform Setup
        run: task verify:terraform

      - name: Format Check
        run: task infra:fmt

      - name: Run Linting
        run: task infra:lint

      - name: Initialize Terraform
        run: task infra:init ENV=dev

      - name: Validate Infrastructure
        run: |
          cd terraform
          terraform validate

      - name: Plan Infrastructure Changes
        if: github.event_name == 'pull_request'
        run: task infra:plan ENV=dev
        continue-on-error: true

      - name: Apply Infrastructure Changes
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: task infra:apply ENV=dev
        env:
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }} 